## Deploy Issuer ##

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: pranav.dhope@gmail.com    
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01: 
       ingress:
         class: gce 

---
## Deploy LetsEncrypt Certificate ##

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-crt
spec:
  secretName: letsencrypt-staging-tls
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging
  commonName: website.local
  dnsNames:
  - apache.website.local

---
## Deploy Ingress ##

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress-tls
  annotations:
    kubernetes.io/ingress.global-static-ip-name: my-static-ip2
    kubernetes.io/ingress.allow-http: "true"
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - apache.website.local
    - nginx.website.local
    secretName: letsencrypt-staging-tls
  rules:
  - host: apache.website.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: myapp1-service
              port:
                number: 9090  
  